- id: 1
  key: renminbi
  code: cny
  symbol: "¥"
  coin: false
  precision: 2
  assets:
    accounts:
      -
        bank: '招商银行'
        address: '6225 0885 6022 3501'
        password: '111111'
        tel: '95555'
- id: 2
  key: satoshi
  qr: btc
  code: btc
  symbol: "฿"
  coin: true
  quick_withdraw_max: 0
  rpc: http://realpointseumailcom:99k9dbjfbdjuq@127.0.0.1:18332
  blockchain: https://blockchain.info/tx/#{txid}
  address_url: https://blockchain.info/address/#{address}
  assets:
    accounts:
      -
        address: 17WwQp6MiBVvjPexzqms6fG37wfAzEEfqP
- id: 3
  key: realpointcoin
  qr: realpointcoin
  code: rpt
  symbol: "RPT"
  coin: true
  quick_withdraw_max: 0
  rpc: http://rptfjdbhfusrjbfvhv:13ucW16WZ2wfdf24234Qkxgc5duEeJrAqQEzcJ12bvP8ymB@127.0.0.1:16501
  blockchain: http://rptblockchain.com/tx/#{txid}
  address_url: http://rptblockchain.com/address/#{address}
  assets:
    accounts:
      -
        address: Rg5SkcAg4RJD9jzCMZBUXuYAtysLS7QA8R
- id: 4
  key: tritiumcoin
  qr: tritium
  code: trt
  symbol: "TRT"
  coin: true
  quick_withdraw_max: 0
  rpc: http://trt834yhbhfusrjbfvhv:15fjngjf3udf24234Qkxgc5duEeJrAqQEzcJ12bvP8ymB@127.0.0.1:17501
  blockchain: http://54.68.252.115/tx/#{txid}
  address_url: http://54.68.252.115/address/#{address}
  assets:
    accounts:
      -
        address: TUaaqmXAasupjnozJ9fQekUcXsfemMTXbK
