- id: 200
  key: satoshi
  currency: btc
  sort_order: 1
  min_confirm: 1
  max_confirm: 3
- id: 400
  key: bank
  currency: cny
  sort_order: 2
  bank_accounts:
    -
      bank: 'Your Bank Name'
      branch: 'Your Bank Branch'
      holder: 'Your Account Holder'
      account: 'Your Account Number'
- id: 1000
  key: realpointcoin
  currency: rpt
  sort_order: 1
  min_confirm: 1
  max_confirm: 8
- id: 1100
  key: tritiumcoin
  currency: trt
  sort_order: 1
  min_confirm: 1
  max_confirm: 8
- id: 401
  key: lamda
  currency: usd
  sort_order: 2
- id: 402
  key: lamda
  currency: eur
  sort_order: 2
